use_frameworks!

platform :ios, '12.0'

target 'UICodeKit_Example' do
  pod 'UICodeKit', :path => '../'
  pod "TinyConstraints"

  target 'UICodeKit_Tests' do
    inherit! :search_paths

    
  end
end
